INSERT INTO Trainee (traineeid, name) VALUES (1, 'Sam Kirk')
INSERT INTO Trainee (traineeid, name) VALUES (2, 'Jarad Huggard')
INSERT INTO Trainee (traineeid, name) VALUES (3, 'Daryl Conway')
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (1, 'java', '5', 1)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (2, 'javascript', '4', 1)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (3, 'java', '5', 2)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (4, 'javascript', '3', 2)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (5, 'java', '4', 3)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (6, 'javascript', '1', 3)