INSERT INTO Trainee (traineeid, name) VALUES (1, 'Sam K')
INSERT INTO Trainee (traineeid, name) VALUES (2, 'Jarad H')
INSERT INTO Trainee (traineeid, name) VALUES (3, 'Daryl C')
INSERT INTO Trainee (traineeid, name) VALUES (4, 'Hussein T')
INSERT INTO Trainee (traineeid, name) VALUES (5, 'Benny W')
INSERT INTO Trainee (traineeid, name) VALUES (6, 'George T')
INSERT INTO Trainee (traineeid, name) VALUES (7, 'Ekaterina G')
INSERT INTO Trainee (traineeid, name) VALUES (8, 'Christopher D')
INSERT INTO Trainee (traineeid, name) VALUES (9, 'Nawid M')
INSERT INTO Trainee (traineeid, name) VALUES (10, 'Michael M')
INSERT INTO Trainee (traineeid, name) VALUES (11, 'Oliver L')
INSERT INTO Trainee (traineeid, name) VALUES (12, 'Naomi')
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (1, 'java', '5', 1)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (2, 'javascript', '4', 1)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (3, 'java', '5', 2)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (4, 'javascript', '3', 2)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (5, 'java', '4', 3)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (6, 'javascript', '1', 3)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (7, 'java', '4', 4)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (8, 'javascript', '1', 4)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (9, 'java', '4', 5)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (10, 'javascript', '1', 5)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (11, 'java', '4', 6)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (12, 'javascript', '1', 6)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (13, 'java', '4', 7)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (14, 'javascript', '1', 7)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (15, 'java', '4', 8)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (16, 'javascript', '1', 8)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (17, 'java', '4', 9)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (18, 'javascript', '1', 9)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (19, 'java', '4', 10)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (20, 'javascript', '1', 10)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (21, 'java', '4', 11)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (22, 'javascript', '1', 11)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (23, 'java', '4', 12)
INSERT INTO Subjects (subject_id, subjectname, skilllevel, traineeid) VALUES (24, 'javascript', '1', 12)